# Generated by Django 4.0.4 on 2022-09-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(default='producto', max_length=15)),
                ('precio', models.PositiveIntegerField()),
                ('thumb', models.ImageField(upload_to='pimg/')),
                ('type', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(default='producto', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='marketplace.trabajos')),
                ('cincoCm', models.PositiveIntegerField()),
                ('diezCm', models.PositiveIntegerField()),
                ('quinceCm', models.PositiveIntegerField()),
                ('veinteCm', models.PositiveIntegerField()),
                ('treintaCm', models.PositiveIntegerField()),
                ('cincuentaCm', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('color', models.CharField(default='Negro', max_length=25)),
                ('tamañoDiseño', models.CharField(default='null', max_length=10)),
                ('precioUnitario', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('nombre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='marketplace.productofijo')),
                ('propietario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
