# Generated by Django 4.0.4 on 2022-10-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_cartproduct_ordenpago_cartproduct_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precios',
        ),
        migrations.DeleteModel(
            name='Trabajos',
        ),
    ]
