# Generated by Django 4.0.4 on 2022-11-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_rename_cantidades_productofijo_cantidaddisponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofijo',
            name='precioCompra',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
